# Generated by Django 4.1.7 on 2023-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrngkddjango4', '0003_student_city_alter_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
